server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easycoding_fast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  main:
    allow-bean-definition-overriding: true
